version: "3"
services:
  api:
    container_name: backend
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8000:3000"
    volumes:
      - .:/usr/src/app/
  postgres:
    container_name: postgres
    image: postgres:10.4
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .env